# contains errors related to static error lint errors.

name: Static Checks

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master

jobs:
  check_base_branch:
    runs-on: ubuntu-18.04
    if: github.event_name == 'pull_request'
    steps:
      - name: "Branch is not based on develop or release branch"
        if: ${{ github.base_ref != 'develop' && !startsWith(github.base_ref,'release-') }}
        run: |
          echo "Current branch is $BASE_BRANCH"
          echo "Note: this check is expected to fail for chained PRs so that they can't accidentally be merged. PRs should only ever be merged directly into develop or a release branch."
          exit 1
        env:
          BASE_BRANCH: ${{ github.base_ref }}